# application.properties (API Gateway)

spring.application.name=api-gateway
server.port=9000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Routes
spring.cloud.gateway.routes[0].id=avis-service
spring.cloud.gateway.routes[0].uri=lb://avis_notificatio-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/avis/**

spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://invitation_notification-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/notification/**
